/*
 * 011I2C_Master_Rx_Test.c
 *
 *  Created on: Jan 4, 2025
 *      Author: engineering
 */

#include "stm32f407xx_i2c_driver.h"
#include <string.h>
#include <stdio.h>

extern void initialise_monitor_handles();

#define I2C1_AF_MODE		4
#define SLAVE_ADDR			0x68
#define MAX_LEN				32

#define CMD_GET_LEN			0x51
#define CMD_RCV_DATA		0x52

uint8_t txBuffer[MAX_LEN] = "STM32 Slave mode test...";

void delay(void)
{
	for (uint32_t i = 0; i < 500000/2; i++);
}

void GPIO_ButtonInit(void)
{
	GPIO_Handle_t gpioLed;

	// Set the base address to GPIO Port D
	gpioLed.pGPIOx = GPIOD;

	// Set pin configuration
	gpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;		// The LED we are toggling is the green onboard LED connected to pin 12 on port D
	gpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	gpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	gpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;	// Set to push-pull output type
	gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&gpioLed);

	GPIO_Handle_t gpioButton;

	// Set base address to GPIO port A
	gpioButton.pGPIOx = GPIOA;

	// Set pin configuration
	gpioButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	gpioButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	gpioButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	gpioButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	GPIO_Init(&gpioButton);
}

I2C_Handle_t I2C1Handle;
void I2C1_Init(void)
{
	/**
	 * PB6 --> I2C1_SCL
	 * PB7 --> I2C1_SDA
	 * ALT function mode: 4
	 */
	// Initialize the GPIO pins to be used for I2C1 peripheral
	I2C_GPIOInit(GPIOB, I2C1_AF_MODE, GPIO_PIN_NO_6, GPIO_PIN_NO_7);

	// Configure I2C Handle for I2C1
	memset(&I2C1Handle, 0, sizeof(I2C1Handle));

	I2C1Handle.pI2Cx = I2C1;
	I2C1Handle.I2C_Config.I2C_ACKControl = I2C_ACK_ENABLE;
	I2C1Handle.I2C_Config.I2C_DeviceAddress = SLAVE_ADDR;
	I2C1Handle.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;		// Doesn't really matter since we are in standard mode
	I2C1Handle.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;		// 100kHz

	// Initialize SPI2
	I2C_Init(&I2C1Handle);
}

void waitForButtonInput()
{
	// Wait until the button is pressed
	while(!GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0));

	// Delay to avoid the button debouncing
	delay();

	// Toggle onboard LED for debugging
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
}

int main(void)
{
	// Initialize to use printf
	initialise_monitor_handles();
	printf("Application is running!\n");

	// Initialize the User button and onboard LED
	GPIO_ButtonInit();

	// Initialize the I2C1 peripheral
	I2C1_Init();

	// I2C IRQ configuration
	I2C_IRQInterruptConfig(IRQ_NO_I2C1_EV, ENABLE);
	I2C_IRQInterruptConfig(IRQ_NO_I2C1_ER, ENABLE);

	// Enable callback events
	I2C_CallbackEventsControl(I2C1Handle.pI2Cx, ENABLE);

	// Enable the I2C1 Peripheral
	I2C_PeripheralControl(I2C1Handle.pI2Cx, ENABLE);

	// Enable ACK if needed
	if(I2C1Handle.I2C_Config.I2C_ACKControl == I2C_ACK_ENABLE)
	{
		I2C_ACKControl(I2C1Handle.pI2Cx, I2C_ACK_ENABLE);
	}

	// Let the program hang and wait for interrupts to occur
	while(1);


	return 0;
}

/**
 * I2C1 ISR Handler Function Implementations
 */

void I2C1_EV_IRQHandler(void)
{
	// Call our driver's EV IRQ Handler
	I2C_EV_IRQHandler(&I2C1Handle);
} // I2C1_EV_IRQHandler

void I2C1_ER_IRQHandler(void)
{
	I2C_ER_IRQHandler(&I2C1Handle);
} // I2C1_EV_IRQHandler

void I2C_ApplicationEventCallback(I2C_Handle_t *pI2CHandle, uint8_t appEv)
{
	static uint8_t commandCode = 0;
	static uint8_t idx = 0;
	if(appEv == I2C_EV_DATA_REQ)
	{
		// Slave send data
		if(commandCode == CMD_GET_LEN)
		{
			printf("Sending length: %d\n", strlen((char*)txBuffer));
			// Send length information to Master
			I2C_SlaveSendData(pI2CHandle->pI2Cx, strlen((char*)txBuffer));
		}
		else if(commandCode == CMD_RCV_DATA)
		{
			printf("Sending character idx: %d\n", idx);
			// Send the contents of txBuffer
			I2C_SlaveSendData(pI2CHandle->pI2Cx, txBuffer[idx++]);
		}
	}
	else if(appEv == I2C_EV_DATA_RCV)
	{
		// Slave receive data
		commandCode = I2C_SlaveReceiveData(pI2CHandle->pI2Cx);
		printf("Received command code: %d\n", commandCode);
	}
	else if(appEv == I2C_ERROR_AF)
	{
		// Slave transmitter mode only
		// In Slave mode AF = 1 indicates that the Master no longer wishes to receive data
		commandCode = 0;
		idx = 0;
	}
	else if(appEv == I2C_EV_STOP)
	{
		// Slave receiver mode only
		// The STOP condition has been generated by the Master, ending communication
	}
}
